In [109]:
import pandas as pd
import numpy as np
import re
from os import listdir
from os.path import isfile, join
from datetime import datetime

In [12]:
cities = ['Amsterdam','LA','Melbourne','NYC','Rio','Tokyo','Venice']
cwd    = os.getcwd()

In [128]:
def get_dir(cwd, group):
    '''Input current directory, sub folders, and return directory of all data files'''
    file_dirs = []
    for g in group:
        sub_dir = os.path.join(cwd, g)
        file_dir = [join(sub_dir,file) for file in listdir(sub_dir) if isfile(join(sub_dir, file))]
        file_dirs = file_dirs + file_dir
    return file_dirs

def read_data(file_dirs, group):
    '''Read directory and get all files as dfs'''
    dfs = []
    for file_dir in file_dirs:
        df = pd.read_csv(file_dir)
        date = re.sub('.csv(.*?)','',re.sub('(.*?)_','',file_dir))
        df['date'] = datetime.strptime(date, '%y-%m-%d')
        a = (g for g in group if g in file_dir)
        df['city'] = a
        dfs.append(df)
    return dfs

In [129]:
dfs = read_data(get_dir(cwd,cities),cities)

#merge all
df = pd.concat(dfs, axis=0, ignore_index=True, sort=False)
df.shape

(778688, 18)

In [130]:
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,date,city
0,2818,Quiet Garden View Room & Super Fast WiFi,3159,Daniel,NaN,Oostelijk Havengebied - Indische Buurt,52.36575,4.94142,Private room,59,3,278,2020-02-14,2.08,1,81,2020-03-13,<generator object read_data.<locals>.<genexpr>...
1,20168,Studio with private bathroom in the centre 1,59484,Alexander,NaN,Centrum-Oost,52.36509,4.89354,Private room,100,1,331,2020-03-11,2.71,2,164,2020-03-13,<generator object read_data.<locals>.<genexpr>...
2,25428,Lovely apt in City Centre (w.lift) near Jordaan,56142,Joan,NaN,Centrum-West,52.37297,4.88339,Entire home/apt,125,14,5,2020-02-09,0.19,1,132,2020-03-13,<generator object read_data.<locals>.<genexpr>...
3,27886,"Romantic, stylish B&B houseboat in canal district",97647,Flip,NaN,Centrum-West,52.38761,4.89188,Private room,155,2,217,2020-03-02,2.18,1,151,2020-03-13,<generator object read_data.<locals>.<genexpr>...
4,28871,Comfortable double room,124245,Edwin,NaN,Centrum-West,52.36719,4.89092,Private room,75,2,329,2020-03-01,2.83,3,146,2020-03-13,<generator object read_data.<locals>.<genexpr>...

In [117]:
df['neighbourhood_group'].value_counts()

City of Los Angeles     93187
Manhattan               89601
Brooklyn                82692
Other Cities            52387
Isole                   28595
Queens                  25064
Unincorporated Areas    11369
Terraferma               6558
Bronx                    4971
Staten Island            1525
Name: neighbourhood_group, dtype: int64